name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Fix PATH
    - name: Restore Python path
      run: |
        echo "PATH=/usr/bin:/usr/local/bin:$PATH" >> $GITHUB_ENV
        echo "Restored PATH = $PATH"

    # Verify python works
    - name: Verify Python
      run: |
        which python3 || true
        /usr/bin/python3 --version

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip unzip git openjdk-17-jdk autoconf libtool pkg-config python3 python3-pip

    - name: Install Python tools
      run: |
        /usr/bin/python3 -m pip install --upgrade pip setuptools wheel
        /usr/bin/python3 -m pip install buildozer cython==0.29.36
        /usr/bin/python3 -m pip install git+https://github.com/kivy/python-for-android.git

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
